### ISSUE TITLE
Http Request Multiplexing

### ISSUE THREAD

**Issue by Kay-Conte** [Kay-Conte/vegemite-rs#5]
Multiplexing is currently blocked by a weird performance issue (about 5x performance decrease in tests) when reading the second response on the same connection. 

- [x] Better error handling of lines reader
- [x] Implement tests for http parsing
- [x] Fully implement multiplexing

**Comment by anthonysSlab** [comment]
could give a shot makin the line reader

**Comment by Kay-Conte** [comment]
Marking this as complete as of v0.2.0

**Comment by anthonysSlab** [comment]
well ye were fasteeree
